export class AppError extends Error {
  constructor(
    public code: string,
    message: string,
    public statusCode: number = 500,
    public details?: Array<{ field: string; message: string }>
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export const ErrorCodes = {
  // Validation (422)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_RANGE: 'INVALID_RANGE',
  INVALID_ENUM: 'INVALID_ENUM',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_RUT: 'INVALID_RUT',
  INVALID_UUID: 'INVALID_UUID',

  // Not Found (404)
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  RECEPTION_NOT_FOUND: 'RECEPTION_NOT_FOUND',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  /** Alias genérico 404 (mismo valor que RESOURCE_NOT_FOUND) */
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  /** Alias genérico 400 (mismo valor que VALIDATION_ERROR) */
  BAD_REQUEST: 'VALIDATION_ERROR',

  // Conflict (409)
  DUPLICATE_SKU: 'DUPLICATE_SKU',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_RUT: 'DUPLICATE_RUT',
  DUPLICATE_CODE: 'DUPLICATE_CODE',
  DUPLICATE_ACCOUNT_CODE: 'DUPLICATE_ACCOUNT_CODE',
  CONFLICT_STATE: 'CONFLICT_STATE',

  // Business (422)
  INVALID_STOCK: 'INVALID_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INVALID_DISCOUNT: 'INVALID_DISCOUNT',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  INVALID_ORDER_STATE: 'INVALID_ORDER_STATE',
  ORDER_ALREADY_PROCESSED: 'ORDER_ALREADY_PROCESSED',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  PAYROLL_PERIOD_CLOSED: 'PAYROLL_PERIOD_CLOSED',
  ACCOUNTING_ENTRY_ALREADY_POSTED: 'ACCOUNTING_ENTRY_ALREADY_POSTED',
  INVALID_ACCOUNTING_ENTRY: 'INVALID_ACCOUNTING_ENTRY',
  INVALID_ACCOUNT_HIERARCHY: 'INVALID_ACCOUNT_HIERARCHY',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  INVALID_PERIOD: 'INVALID_PERIOD',

  // Auth (401/403)
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ROLE_REQUIRED: 'ROLE_REQUIRED',

  // Server (500)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  PROCESSING_ERROR: 'PROCESSING_ERROR',

  // Rate Limit (429)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
} as const;

